### ISSUE TITLE
Use the new SVG for MapLibre

### ISSUE THREAD

**Issue by HarelM** [maplibre/ngx-maplibre-gl#129]
Recently there was a change in the maplibre icon.
See here:
https://maplibre.org/
This PR:
https://github.com/maplibre/maplibre.github.io/pull/275

**Comment by HarelM** [comment]
cc: @birkskyum do you have the svg for the marker only and not marker + text?

**Comment by birkskyum** [comment]
Sure, here are some. It's with background because github can be both light/dark and doesn't give us any way to swap the logo depending on the background...

![marker-blue](https://github.com/maplibre/ngx-maplibre-gl/assets/74932975/c1ed4a56-86c2-44ad-bbd0-6797ff306b58)


![marker](https://github.com/maplibre/ngx-maplibre-gl/assets/74932975/0a57b9d7-85fe-4737-995f-166ae740931d)

**Comment by HarelM** [comment]
@marcjulian any chance you can help here? I'm not good with SVGs...
