### ISSUE TITLE
Rename css classes

### ISSUE THREAD

**Issue by aprilmay** [maplibre/ngx-maplibre-gl#4]
Maplibre 1.15.0 introduces a breaking change: css class names renamed from `mapboxgl-*` to `maplibregl-*` (see https://github.com/maplibre/maplibre-gl-js/blob/main/CHANGELOG.md, https://github.com/maplibre/maplibre-gl-js/issues/83)

ngx-maplibre-gl 's css classes names should match this change.

**Comment by HarelM** [comment]
I wasn't aware this project had css in it...
Care to submit a PR to resolve this?

**Comment by HarelM** [comment]
BTW, any help with the other two issues I just opened would be greatly appreciated!

**Comment by bendman** [comment]
The [suggestion of keeping both classes](https://github.com/maplibre/maplibre-gl-js/issues/83#issuecomment-781433685) might have prevented it from being a breaking change, and a minor semver bump would have made sense. 

As it stands, this introduced a breaking change without the requisite semver major bump, so it might cause issues for consumers of this package. I know it did for us!

**Comment by aprilmay** [comment]
> The [suggestion of keeping both classes](https://github.com/maplibre/maplibre-gl-js/issues/83#issuecomment-781433685) might have prevented it from being a breaking change, and a minor semver bump would have made sense.
> 
> As it stands, this introduced a breaking change without the requisite semver major bump, so it might cause issues for consumers of this package. I know it did for us!

Same here, actually it triggered this update. Since that breaking change was pushed to maplibre-gl-js, do we have much choice here?

**Comment by bendman** [comment]
No, I think it's a backwards compatibility issue with maplibre not using semver correctly. We are doing a similar change in our internal libraries as you do in yours.

**Comment by HarelM** [comment]
I basically pushed this to maplibre-gl.
I actually asked if the change in css should be major or minor and other have agreed it was minor and not major.
The extra size in the package is critical so duplicating the styles was not a recommended step.
Also, since not many people are using maplibre yet we agreed that pushing this forward early on would be the right step.
In any case, feel free to join the slack and github issues communication and share your opinion.
Bare in mind that some opinions will be accepted and other won't, this is the open source way :-)
