### ISSUE TITLE
Slow performance

### ISSUE THREAD

**Issue by Ste-denko** [maplibre/ngx-maplibre-gl#47]
The overall performance of the map is slow.
The map itself and also layer elements are loading and shown slowly.
As a source I am using:
https://api.maptiler.com/maps/streets/style.json?key=myKey

The map loading and also the loading of layer elements in comparison with [ngx-mapbox-gl](https://github.com/Wykks/ngx-mapbox-gl) is much faster.
ngx-mapbox-gl is hereby also using another map source.

What can be done to improve the performance of ngx-maplibre-gl ?

**Comment by HarelM** [comment]
I'm not sure I know how to answer this question.
There's not a lot of code in this library, it's basically a thin Angular wrapper around maplibre-gl.
Having said that, I do think it's not very performant as it uses the Angular cycles to update the map on high interval which is not the case when using maplibre-gl without this wrapper.
I don't feel like I'm experiencing performance issues, but my two cents would be to measure the performance so we can talk about data and not about feelings :-)
I'm also guessing that following Angular tips in order to improve performance will help in this case as well (change detection, onPush etc).
I've tried in the past to open chrome tools and try and find the performance bottle necks but failed miserably.
Any help in this area would be greatly appreciated! :-)

**Comment by webberig** [comment]
> The map loading and also the loading of layer elements in comparison with [ngx-mapbox-gl](https://github.com/Wykks/ngx-mapbox-gl) is much faster.

This is very weird, because this repo is nothing more than a fork of ng-mapbox-gl. Can you determine if the difference is related to mapbox-gl vs maplibre-gl or is the bottleneck coming from the Angular bindings ?

**Comment by Ste-denko** [comment]
I am not sure what exactly may cause the difference but I dont think that this is code related.
To me the different styles/sources that are used are most suspicious since this is the only real difference.
Does one of you have experience with that, if the different styling source may cause this?
By the way ... are tiles or vectors used as a default in the map?

**Comment by hheexx** [comment]
Any estimate on amount of work to move components to OnPush ?

**Comment by HarelM** [comment]
I think you can use onPush today too with the components here, can't you?
In any case, I'm not very familiar with this topic so if someone is willing to push this forward I'll be happy to review the changes :-)

**Comment by HarelM** [comment]
Since this is stale and I don't think there's much to do here without a specific example or problem statement, I decided to close this issue.
Feel free to continue writing here or open a more specific issue in the future.
Even better, open a PR to fix the specific problem you are facing :-)
